config/routes.rb
Rails.application.routes.draw do

  root 'tvshows#index'  
  resources :tvshows do 
    resources :user_reviews, only: [:create, :new]
  end

end

app/models/tvshow.rb
class Tvshow < ActiveRecord::Base
  has_many :user_reviews
end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
  belongs_to :tvshow
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  def index
    @tvshow = Tvshow.all

  end

  def show
    @tvshow = Tvshow.find(params[:id])
  end
end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  def create
    @tvshow = Tvshow.find(params[:tvshow_id])
    @tvshow.user_reviews.create(user_review_params)
    redirect_to tvshow_path(@tvshow)
  end

  def new
    @tvshow = Tvshow.find(params[:tvshow_id])
    @user_review = UserReview.new
  end

  private

  def user_review_params
    params.require(:user_review).permit(:review, :rating, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1 class='colorize'>Willie's favorite TV Shows</h1>

  <%= yield %>

</body>
</html>

app/views/tvshows/index.html.erb
<% @tvshow.each do |tvshow| %>
  <h1><%= tvshow.name %></h1>
  <p><%= tvshow.description %></p>
  <i>Star Rating: <%= tvshow.star_rating %></i>

  <br />

  <i>
    <%= link_to "User Reviews", tvshow_path(tvshow) %>
  <br />
    <%= link_to "Submit Your Own Review", new_tvshow_user_review_path(tvshow) %>
  </i>

  <hr />
<% end %>

app/views/tvshows/show.html.erb
<% if @tvshow.user_reviews.empty? %>
  <h2> No User Reviews Have Been Submitted Yet.</h2>
  <hr />
<% else %>
  <h1><%= @tvshow.name %></h1>

  <% @tvshow.user_reviews.each do |reviews| %>
    <h2> <%= reviews.review %> </h2>
    <h2> <%= reviews.rating %> </h2>
    <h2> <%= reviews.name %> </h2>
    
    <hr />
  <% end %>
<% end %>

<h2><%= link_to "Submit Your Own Review", new_tvshow_user_review_path(@tvshow.id) %></h2> 

app/views/user_reviews/new.html.erb
<h1>Submit your own review!</h1>
<%= simple_form_for @user_review, url: tvshow_user_reviews_path(@tvshow) do |f| %>
  <%= f.input :review %>
  <%= f.input :rating %>
  <%= f.input :name %>
  <%= f.submit "Add a Review", class: 'btn btn-primary' %>
<% end %>